= 1.2.0

Update focuses more on general experience of the game and removing bugs. Not very much focus on the UX or content.

== General

* adds basic start splash after main splash that allows the player to set their name
* adds basic tutorial dialogue with the bus driver.
* updates text special colors.

== Content

* fixed the conversations so the "the Mechanic", "a Runner Up", "Got the Message", and "Never Made It" achievements are now possible.
* added achievement "Fix a Flat", "a Short Hike", and "There and Back Again".
* updated descriptions for items.
* updated choice display for actions to be uniform.
* adds bus and podium graphics, adjusted placement of others.

== Backend Stuff

* adds ability to set and load lifetime values from the dialogue editor.

== Fixes

* fixes bug where boarding the bus would create a _TON_ of extra cycles.
* fixes bug where lifetime values like `cycles` would not save. 
* fixes bug where the `progress screen` wasn't counting achievements.
* fixes bug that would prevent the name-intro screen from appearing the same cycle you clear your data / also fixes the issue where you can reset mid cycle and it didn't restart the cycle.
* fixes issue where not all location visits are using up "slots" in a "period" (more than 2 visits per time point).
* fixes "ghost" character icons on locations.
* fixes text formatting display issues, which caused the formatting symbols to not be removed and be displayed in the text.
* rudamental underlines for links on the splash so its a little more obvious whats going on.
