= General

issues that cannot be categorized.

== Open

* [ ] make the player able to change their name.

* [ ] need a cycle summary page that tells you what you've accomplished at the end of each cycle. gives some "outro text" on certain questlines that you accomplish.

* [ ] change cursor icon to normal so people don't think its a button.

	interactives automatically change the cursor to the finger, need to review all instances and change it to the normal curser (because i use interactives as a way to disable other interactives ...) so that the cursor actually expresses whats going on.


* [ ] put the text on an different layer that doesn't scale, so if the game resolution is 1080p, i want to the text to be renderd in 1080p, not in the game native resolution and then scaled up to 1080p

* [ ] a UI screen / tab that tracks where everyone is, shows possible locations for people, if you've encountered them.

== Completed

* [x] player needs to be able to set their name, combine with the tutorial?
* [x] pick a background color
* [x] the dialogue has weird width correction, looks bad.
* [x] it looks like some text formatting isn't working?
* [x] dialogue choice wheel should change diameter based on choice options.

	kind of fixed this one, now a stack instead of a wheel.

* [x] the ui is drawn over the text in some cases (inventory and dialogue)

	i think this is fixed for the most part. the biggest issue was the text on the map, for the locations. i fixed this when i updated the location font.

