= Next Release

== General

* adds basic start splash after main splash that allows the player to set their name
* adds basic tutorial dialogue with the bus driver.

== Content

* fixed the conversations so the "the Mechanic", "a Runner Up", "Got the Message", and "Never Made It" achievements are now possible.
* added achievement "Fix a Flat", "a Short Hike", and "There and Back Again".
* updated descriptions for items.
* updated choice display for actions to be uniform.

== Backend Stuff

* adds ability to set and load lifetime values from the dialogue editor.

== Fixes

* fixes bug where boarding the bus would create a _TON_ of extra cycles.
* fixes bug where lifetime values like `cycles` would not save. 
* fixes bug where the `progress screen` wasn't counting achievements.
* fixes bug that would prevent the name-intro screen from appearing the same cycle you clear your data / also fixes the issue where you can reset mid cycle and it didn't restart the cycle.
* fixes issue where not all location visits are using up "slots" in a "period" (more than 2 visits per time point).
* fixes "ghost" character icons on locations.

= 1.1.0

== General

* adds ability to carry objects to the next *cycle*.

== Cosmetic

* changes font for on-map location name.
* updates splash to have 2 columns for fonts.
* updated main conversation font to have '$' symbol.
* fixes the "drift" with dancing text.

== Credits

* updates the fonts that are used on the front splash.

== Fixes

* fixes the discrepancies  between the backpack and what the player actually has, unified them so now the backpack accurately represents what the user has.
* fixes a bug that causes the first action in a new cycle to take up one of your action slots, effectively limiting you to only 1 action that first period.