= For Current Release Target.

== General

- [ ] make the player able to change their name.
- [x] player needs to be able to set their name, combine with the tutorial?
- [x] pick a background color
- [x] the dialogue has weird width correction, looks bad.
- [x] it looks like some text formatting isn't working?
- [x] dialogue choice wheel should change diameter based on choice options.

	kind of fixed this one, now a stack instead of a wheel.

- [x] the ui is drawn over the text in some cases (inventory and dialogue)

	i think this is fixed for the most part. the biggest issue was the text on the map, for the locations. i fixed this when i updated the location font.

== Backpack

- [x] fix the background drawing for the backpack icon, it "forgets" to draw the background sometimes.
- [x] select final background color
- [x] change the font for the title / description to fit better.

== Clock

- [x] fix the display of "check the time", it is too narrow and tall.
- [ ] i made a better way to remove the wheel with the sun / clock item. refactor the scene's version of that (the fake interactive) with this way instead.

== Content

- [x] make ability to 'carry over' an item to the next cycle.
- [x] make all achievements possible.
- [x] add the message in the bottle quest.
- [x] draw a podium
- [X] draw a bus
- [ ] create a tutorial conversation that explains some things for the first run.
- [ ] fox needs to have some dialogue for if you see them in the mechanic shop and the car is still broken.

== Conversations

- [x] fix the italics font, doesn't look plesant

	changed the font to the same one that i'm using for the action, just with a different color. looks better.

- [x] fix the dancing text, it seems to "run away"

	the issue was that i was adding and subtracting the sin-wave from the location, but since it isn't doing the same points every time (it is determine the angles based on dt) it would not be starting the loop at the same position. i couldn't just reset the position because i was moving it round independent of the dancing (an issue) so instead i updated the loop that on the first timer update it logs the location (whcih should be the original starting position) and it resets it whenever it ends the timer and resets the animation. works but looks funky.

- [x] select final background an bubble color / appearance
- [x] chosen dialogue font doesn't have a `$`

	seems that the font had the `$` symbol, but it wasn't exported to the bitmap font .. so i fixed that. 

== Items

- [ ] the coffee skill doesn't work as expected.

== Map

- [x] update how the character icon determined, so that we don't get duplicates.

	updated how the `seen` but works, it still does the same thing, if you see someone at a location it logs it, but now it will actually check against where the character actually is before displaying it on the map, this way it will accurately show someone on the map if they are in that location, and will not show duplicate people (based on divergent paths that could occur when you do different actions with those people).

- [x] when disabling the locations for this period, should also "disable" the background so it fits more.
- [x] update the location name font

== Menu

- [x] finalize the main title font.
- [x] reduce the "a game by" font size.


== Menu (Game)

- [x] rework achievements menu to show icons.
- [x] add conversations to the *progress* tracking. (per character)

== Javascript

- [x] data saving & loading

= For Next Target Release.

== Content

- [ ] make the cat's dialogue in the game.
- [ ] make props for the park
- [ ] make props for the cafe
- [ ] make props for the office
- [ ] make alternate lamb without clipboard
- [ ] make alternate fox without apron
- [ ] draw the market grocer character / (make him fish).

== Conversations

- [ ] color or group conversation choices by topic, so you know what is connected to what idea / quest.

== Map

- [ ] update how the character icons are displayed, make them stand out more.

== Menu

- [ ] a UI screen / tab that tracks where everyone is, shows possible locations for people, if you've encountered them.