= Secret Santa 2020 v1

Notes for the first iteration design of the secret santa entry.

== Secret Santa Letter

[quote, xxxx, Introduction letter.]
____
Dear Santa,

Hi there! I'm a game developer! I love RPGs because they are always so immersive and they make me feel like I am actually part of the story. 

I also really enjoy puzzle games, for example: Human Fall Flat (one of my favourites 😂) , because it is generally fun to use your brain to, you know, solve the puzzles. :smile I would like to have a game with both genres mixed together! To me, it sounds like a good idea. 🤔 

I mostly use my PC, but if you want, you can also export the game to Android! :D Here are some of my previous games, done with some friends in week long game jams (they aren't the best, but i'm proud of them): https://artistic-devs.itch.io/ 
____


[quote, xxxx, 2nd response on interests.]
____
Dear Santa,

Hey! How are you? Some of my favorite sports are: cycling and rollerblading. Talking about hobbies and interests, tell me some of yours! Also, what are some of your favorite video game or video game genres? As you said, it could add that extra flavor, haha!

Love, xxxx
____