= Brainstorming

Working through various ideas.

== Potential Types

Key Points

- Cycling / Rollerblading
- Immersive part of the story
- Puzzles (human fall flat)

=== Grow-Like

A grow like puzzle game.

=== Sports Game

Tactical Turn Based / VN

==== Description

The gameplay is a roller blading kind of arena game where you play against an AI. Probably like football but on rollerblades. Turns are taken together and you have to decide what the AI is going to do and the turns execute together. All about maintaining speed and momentum, and passing the ball.

The immersive story but (outside of the matches) is a visual novel style gameplay where you talk to people and make choices / decisions that effect players and the story somehow.

==== Tech Details

- 2D Sprites, 2D or 3D world.
- would be like that dodgeball game, or pokemon / old fire emblem

=== Jet Set Radio?

3rd Person RPG / Skater

The gameplay is rollerblading and moving around the area. The area is closed off and you have to talk to people, do quests in order to unlock other areas and extend the space that you can access (human fall flat puzzle??).

When you interact with people they give you more information / progress a story forward and some choices you make might give you access to other parts of the area.

==== Tech Details

- simple 3D models, tony hawk style
- could be 2D overhead like pokemon style